# FilterQL Documentation Site

title: "FilterQL"
description: "Dynamic Query Filtering Made Simple - A powerful Java library for dynamic filtering with intuitive DSL"
url: "https://cyfko.github.io"
baseurl: "/filter-build"

# Build settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs

# Configuration Just-the-Docs
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation externe
nav_external_links:
  - title: GitHub
    url: https://github.com/cyfko/filter-build
  - title: Maven Central
    url: https://search.maven.org/artifact/io.github.cyfko/filterql-core

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jemoji

# Navigation structure
header_pages:
  - README.md
  - docs/getting-started.md
  - docs/core-concepts.md
  - docs/spring-adapter.md
  - docs/jpa-adapter.md
  - docs/ARCHITECTURE.md

# Repository information for GitHub metadata
repository: cyfko/filter-build

# Site metadata
author:
  name: "Frank KOSSI"

github:
  username: cyfko
  repository_name: filter-build

# SEO settings
social:
  name: FilterQL
  links:
    - https://github.com/cyfko/filter-build

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - target/
  - .git/
  - .gitignore
  - .vscode/
  - .idea/
  - core/
  - adapters/
  - "*.jar"
  - "*.log"
  - rapport-conformite-documentation-code.md
  - corrections-documentation-filterql.md

# Include in processing
include:
  - _pages