title: FilterQL Documentation
description: Dynamic Query Filtering Made Simple - A powerful Java library for dynamic filtering with intuitive DSL
theme: jekyll-theme-minimal

# Navigation
nav_links:
  - title: "Home"
    url: "/"
  - title: "Getting Started"
    url: "/getting-started"
  - title: "Core Concepts"
    url: "/core-concepts"
  - title: "Spring Guide"
    url: "/spring-adapter"
  - title: "JPA Guide"
    url: "/jpa-adapter"
  - title: "GitHub"
    url: "https://github.com/cyfko/filter-build"

# Site settings
github:
  repository_url: https://github.com/cyfko/filter-build
  repository_name: cyfko/filter-build

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Code highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false