# FilterQL Documentation - Jekyll Configuration
# Site settings
title: "FilterQL Documentation"
description: "Transform Filtering Forever - Advanced dynamic filtering protocol for Java"
baseurl: "/filter-build"
url: "https://cyfko.github.io"
author: "cyfko"

# Repository info
repository: "cyfko/filter-build"
github_username: "cyfko"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - JEKYLL_TRANSFORMATION_PROMPT.md
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github
  - node_modules
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock

# Include these files in the site
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.md"
    values:
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"

# Navigation structure (preserving exact current structure)
navigation:
  main:
    - title: "Home"
      url: "/"
    - title: "Getting Started"
      url: "/getting-started"
      children:
        - title: "Quick Start"
          url: "/getting-started/quick-start"
    - title: "Core Module"
      url: "/core-module"
      children:
        - title: "Overview"
          url: "/core-module/overview"
    - title: "Spring Adapter"
      url: "/spring-adapter"
      children:
        - title: "Overview"
          url: "/spring-adapter/overview"
    - title: "Examples"
      url: "/examples"
    - title: "FAQ"
      url: "/faq"
    - title: "Troubleshooting"
      url: "/troubleshooting"
    - title: "Architecture"
      url: "/ARCHITECTURE"

# Theme configuration
theme_config:
  logo: "FilterQL"
  github_url: "https://github.com/cyfko/filter-build"
  edit_page: true
  search_enabled: true
  dark_mode: true
  code_copy_button: true

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# SEO and social
twitter:
  username: cyfko
  card: summary

social:
  name: FilterQL
  links:
    - https://github.com/cyfko/filter-build

# Analytics (optional - uncomment if needed)
# google_analytics: G-XXXXXXXXXX

# Performance settings
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Timezone
timezone: UTC